#  Main header!
#  Line 2

[songs]
	[songs.ACelticTale]
		triggers = [ "dimension-overworld" ]
	[songs.ASongFromTheDeep]
		triggers = [ "dimension-overworld" ]
	[songs.Aether1]
		triggers = [ "dimension-aether" ]
	[songs.Aether10]
		triggers = [ "dimension-aether" ]
	[songs.Aether2]
		triggers = [ "dimension-aether" ]
		volume = "0.6"
	[songs.Aether3]
		triggers = [ "dimension-aether" ]
	[songs.Aether4]
		triggers = [ "dimension-aether" ]
		volume = "0.6"
	[songs.Aether5]
		triggers = [ "dimension-aether" ]
		volume = "0.5"
	[songs.Aether6]
		triggers = [ "dimension-aether" ]
		volume = "0.6"
	[songs.Aether7]
		triggers = [ "dimension-aether" ]
		volume = "0.6"
	[songs.Aether9]
		triggers = [ "dimension-aether" ]
	[songs.Alpha]
		triggers = [ "dimension-overworld" ]
	[songs.Alvae]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.BeautifulDreams]
		triggers = [ "dimension-overworld" ]
	[songs.Beneath1]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath10]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath2]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath3]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath4]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath5]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath6]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath7]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath8]
		triggers = [ "dimension-beneath" ]
	[songs.Beneath9]
		triggers = [ "dimension-beneath" ]
	[songs.BlackDeath1]
		triggers = [ "mob-blackdeath" ]
	[songs.BreathOfTheForest]
		triggers = [ "dimension-overworld" ]
	[songs.CastleInTheSky]
		triggers = [ "dimension-overworld" ]
	[songs.CelticLore]
		triggers = [ "dimension-overworld" ]
	[songs.Clarity]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.CrannNaBeatha]
		triggers = [ "dimension-overworld" ]
	[[songs.CrystalForest]]
		triggers = [ "dimension-overworld", "raining" ]
	[[songs.CrystalForest]]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.DeepUnder1]
		triggers = [ "height-deep_underground", "dimension-overworld" ]
	[songs.DeepUnder2]
		triggers = [ "height-deep_underground", "dimension-overworld" ]
	[songs.DeepUnder3]
		triggers = [ "height-deep_underground", "dimension-overworld" ]
	[songs.Deliverance]
		triggers = [ "dimension-overworld" ]
	[songs.DuNock-Street]
		triggers = [ "menu" ]
	[songs.End1]
		triggers = [ "dimension-end" ]
	[songs.End2]
		triggers = [ "dimension-end" ]
	[songs.End3]
		triggers = [ "dimension-end" ]
	[songs.End4]
		triggers = [ "dimension-end" ]
	[songs.End5]
		triggers = [ "dimension-end" ]
	[songs.End6]
		triggers = [ "dimension-end" ]
	[songs.EndCity1]
		triggers = [ "structure-endcity" ]
	[songs.EndCity2]
		triggers = [ "structure-endcity" ]
	[songs.Eventide]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.FarBeyond]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.ForTheKing]
		triggers = [ "dimension-overworld" ]
	[songs.Fort1]
		triggers = [ "structure-stronghold" ]
	[songs.Fort2]
		triggers = [ "structure-stronghold" ]
	[songs.Fort3]
		triggers = [ "structure-stronghold" ]
	[songs.Fort4]
		triggers = [ "structure-stronghold" ]
	[songs.Fort5]
		triggers = [ "structure-stronghold" ]
	[songs.Freedom]
		triggers = [ "dimension-overworld" ]
	[songs.Frostmaw]
		triggers = [ "mob-frostmaw" ]
	[songs.FrozenInTime]
		triggers = [ "dimension-overworld", "raining" ]
	[songs.GlacierDay1]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.GlacierDay2]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.GlacierNight1]
		triggers = [ "dimension-overworld", "biome-snowy", "time-night" ]
	[songs.GlacierNight2]
		triggers = [ "dimension-overworld", "biome-snowy", "time-night" ]
	[songs.Hirschgeist1]
		triggers = [ "mob-hirschgeist" ]
	[songs.IcyDay1]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.IcyDay2]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.IcyDay3]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.IcyNight1]
		triggers = [ "dimension-overworld", "biome-snowy", "time-night" ]
	[songs.IcyNight2]
		triggers = [ "dimension-overworld", "biome-snowy", "time-night" ]
	[[songs.IntoSilenceP1]]
		triggers = [ "dimension-overworld", "raining" ]
	[[songs.IntoSilenceP1]]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.InvasionSong]
		triggers = [ "mob-horde" ]
	[songs.KeeperOfTheForest]
		triggers = [ "dimension-overworld" ]
	[songs.KingdomOfBards]
		triggers = [ "dimension-overworld" ]
	[songs.LastStand]
		triggers = [ "mob-enderdragon" ]
	[songs.Mirrormere]
		triggers = [ "dimension-overworld" ]
	[[songs.Moonsong]]
		triggers = [ "dimension-overworld", "raining" ]
	[[songs.Moonsong]]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.Mourning]
		triggers = [ "dimension-overworld" ]
	[songs.Myth]
		triggers = [ "dimension-overworld" ]
	[songs.NFortress1]
		triggers = [ "structure-nether_fortress" ]
	[songs.NFortress2]
		triggers = [ "structure-nether_fortress" ]
	[songs.NFortress3]
		triggers = [ "structure-nether_fortress" ]
	[songs.Nether1]
		triggers = [ "dimension-nether" ]
	[songs.Nether2]
		triggers = [ "dimension-nether" ]
	[songs.Nether3]
		triggers = [ "dimension-nether" ]
	[songs.Nether4]
		triggers = [ "dimension-nether" ]
	[songs.Nether5]
		triggers = [ "dimension-nether" ]
	[songs.Nether6]
		triggers = [ "dimension-nether" ]
	[songs.Nether7]
		triggers = [ "dimension-nether" ]
	[songs.Nether8]
		triggers = [ "dimension-nether" ]
	[songs.NetherDepths]
		triggers = [ "dimension-nether" ]
	[songs.NeverToReturn]
		triggers = [ "dimension-overworld" ]
	[songs.Night1]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.Night2]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.NightAtTheEolian]
		triggers = [ "dimension-overworld" ]
	[songs.NightoftheFae]
		triggers = [ "dimension-overworld" ]
	[songs.OdeToTheFallen]
		triggers = [ "dimension-overworld" ]
	[songs.Quazar]
		triggers = [ "mob-quazar" ]
	[songs.QuestsEnd]
		triggers = [ "dimension-overworld", "raining" ]
	[songs.Reverie]
		triggers = [ "dimension-overworld" ]
	[songs.Ruthless]
		triggers = [ "mob-any_boss" ]
	[songs.Ruthless2]
		triggers = [ "mob-any_boss" ]
	[songs.Ruthless3]
		triggers = [ "mob-any_boss" ]
	[songs.SacredEarth]
		triggers = [ "dimension-overworld" ]
	[songs.ShimmeringInTheShallows]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.SiochainShuthain]
		triggers = [ "dimension-overworld" ]
	[songs.Sleeper]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.SnowQueen1]
		triggers = [ "mob-snowqueen" ]
	[songs.Storm]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.SunChief]
		triggers = [ "mob-sunchief" ]
	[songs.TForest1]
		triggers = [ "dimension-twilightforest" ]
	[songs.TForest2]
		triggers = [ "dimension-twilightforest" ]
	[songs.TForest3]
		triggers = [ "dimension-twilightforest" ]
	[songs.TForest4]
		triggers = [ "dimension-twilightforest" ]
	[songs.TForest5]
		triggers = [ "dimension-twilightforest" ]
	[songs.TheHarvester]
		triggers = [ "mob-harvester" ]
	[songs.TheShapersRealm]
		triggers = [ "dimension-twilightforest" ]
	[songs.Underground1]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground10]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground11]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground2]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground3]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground4]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground5]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground6]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground7]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground8]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Underground9]
		triggers = [ "height-underground", "dimension-overworld" ]
	[songs.Wanderer]
		triggers = [ "dimension-overworld" ]
	[songs.WhatLiesBeyond]
		triggers = [ "dimension-overworld" ]
	[songs.WhereIBelong]
		triggers = [ "dimension-overworld" ]
	[songs.WildfireP1]
		triggers = [ "dimension-overworld" ]
	[songs.WildfireP2]
		triggers = [ "dimension-overworld" ]
	[[songs.WintersNight]]
		triggers = [ "dimension-overworld", "biome-snowy", "time-night" ]
	[[songs.WintersNight]]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.WintersSong]
		triggers = [ "dimension-overworld", "biome-snowy" ]
	[songs.Wither]
		triggers = [ "mob-wither" ]
	[songs.Wither2]
		triggers = [ "mob-wither" ]
	[songs.WoodlandTales]
		triggers = [ "dimension-overworld" ]
	[[songs.WorldUnbound]]
		triggers = [ "dimension-overworld", "raining" ]
	[[songs.WorldUnbound]]
		triggers = [ "time-night", "dimension-overworld" ]
	[songs.Wroughtnaut]
		triggers = [ "mob-wroughtnaut" ]
	[songs.demoniachorus]
		triggers = [ "dimension-beneath" ]
	[songs.universal]
		pitch = 1.0
		play_once = 0
		speed = 1.0
		volume = 1.0
		[songs.universal.interrupt_handler]
			priority = 2147483647
			trigger_whitelist = [ ]

[triggers]
	[triggers.biome]
		biome_tag = [ "snowy" ]
		identifier = "snowy"
		resource_name = [ "snowy", "ice", "glacier", "frozen", "cold" ]
	[[triggers.dimension]]
		identifier = "aether"
		priority = "100"
		resource_name = [ "4" ]
	[[triggers.dimension]]
		identifier = "overworld"
		resource_name = [ "0" ]
	[[triggers.dimension]]
		identifier = "beneath"
		priority = "100"
		resource_name = [ "10" ]
	[[triggers.dimension]]
		identifier = "twilightforest"
		priority = "50"
		resource_name = [ "7" ]
	[[triggers.dimension]]
		identifier = "nether"
		resource_name = [ "-1" ]
	[[triggers.dimension]]
		identifier = "end"
		priority = "100"
		resource_name = [ "1" ]
	[[triggers.height]]
		identifier = "deep_underground"
		level = "15"
		priority = "10"
	[[triggers.height]]
		identifier = "underground"
		level = "50"
		priority = "10"
	[triggers.menu]
	[[triggers.mob]]
		detection_range = "100"
		detection_y_ratio = "0.25"
		horde_targeting_percentage = "100.0"
		identifier = "horde"
		level = "8"
		persistence = "120"
		priority = "50"
		resource_name = [ "MOB" ]
	[[triggers.mob]]
		detection_range = "50"
		identifier = "any_boss"
		mob_targeting = false
		persistence = "80"
		priority = "100"
		resource_name = [ "BOSS" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "harvester"
		priority = "500"
		resource_name = [ "harvestersnight:harvester" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "wither"
		priority = "500"
		resource_name = [ "minecraft:wither" ]
	[[triggers.mob]]
		detection_range = "300"
		detection_y_ratio = "100.0"
		identifier = "enderdragon"
		mob_targeting = false
		priority = "500"
		resource_name = [ "minecraft:ender_dragon" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "hirschgeist"
		priority = "500"
		resource_name = [ "betteranimalsplus:hirschgeist" ]
	[[triggers.mob]]
		detection_range = "50"
		identifier = "sunchief"
		persistence = "100"
		priority = "500"
		resource_name = [ "mowziesmobs:barako" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "frostmaw"
		priority = "500"
		resource_name = [ "mowziesmobs:frostmaw" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "blackdeath"
		priority = "500"
		resource_name = [ "rats:black_death" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "snowqueen"
		priority = "500"
		resource_name = [ "twilightforest:snow_queen" ]
	[[triggers.mob]]
		detection_range = "100"
		identifier = "quazar"
		priority = "500"
		resource_name = [ "betterslimes:quazar" ]
	[[triggers.mob]]
		detection_range = "10"
		identifier = "wroughtnaut"
		priority = "500"
		resource_name = [ "mowziesmobs:ferrous_wroughtnaut" ]
	[triggers.raining]
	[[triggers.structure]]
		identifier = "nether_fortress"
		persistence = "120"
		priority = "100"
		resource_name = [ "Fortress" ]
	[[triggers.structure]]
		identifier = "stronghold"
		persistence = "120"
		priority = "100"
		resource_name = [ "Stronghold" ]
	[[triggers.structure]]
		identifier = "endcity"
		persistence = "120"
		priority = "100"
		resource_name = [ "EndCity" ]
	[triggers.time]
		identifier = "night"
		time_bundle = "night"
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "20"
		fade_out = "40"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"

