// mud recipe
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 1.0f)
    .input(item('betterwithmods:dirt_pile'))
    .output(item('biomesoplenty:mudball'))
    .register()
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 1.0f)
    .input(item('contenttweaker:silty_dirt_pile'))
    .output(item('biomesoplenty:mudball'))
    .register()
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 1.0f)
    .input(item('contenttweaker:loamy_dirt_pile'))
    .output(item('biomesoplenty:mudball'))
    .register()
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 1.0f)
    .input(item('contenttweaker:sandy_dirt_pile'))
    .output(item('biomesoplenty:mudball'))
    .register()
	
// best durable twine deal
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('wood_tar'), 1.0f)
    .input(item('pyrotech:material:14') * 8)
    .output(item('pyrotech:material:26') * 24)
    .register()
// ground netherrack to nether sludge	
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('blood'), 0.0f)
    .input(item('betterwithmods:material:15'))
    .output(item('betterwithmods:material:35'))
    .register()	
// ground fiery netherrack to fiery sludge
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('blood'), 0.0f)
    .input(item('contenttweaker:ground_fiery_netherrack'))
    .output(item('contenttweaker:fiery_sludge'))
    .register()
// Mysterious vessel
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('blood'), 0.5f)
    .input(item('contenttweaker:crucible_of_souls'))
    .output(item('betterwithmods:cooking_pot:2'))
    .register()
// Cleanse Focus
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('lunar_water'), 0.0f)
    .input(item('contenttweaker:arcane_focus'))
    .output(item('contenttweaker:unattuned_focus'))
    .register()
// broken lance to functional one for legacy inventories
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 0.0f)
    .input(item('aether_legacy:valkyrie_lance:*'))
    .output(item('spartanweaponry:pike_invar'))
    .register()