//minecraft:stone
//quark:world_stone_carved

//<minecraft:prismarine:1>


import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.jei.JEI;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;
import mods.betterwithmods.Anvil;
import mods.betterwithmods.Saw;
import crafttweaker.data.IData;

//remove autogenerated miniblocks
JEI.removeAndHide(<betterwithmods:siding_rock>.withTag({texture: {Name: "minecraft:brick_block"}}));
JEI.removeAndHide(<betterwithmods:siding_rock>.withTag({texture: {Name: "minecraft:nether_brick"}}));

JEI.removeAndHide(<betterwithmods:moulding_rock>.withTag({texture: {Name: "minecraft:brick_block"}}));
JEI.removeAndHide(<betterwithmods:moulding_rock>.withTag({texture: {Name: "minecraft:nether_brick"}}));

JEI.removeAndHide(<betterwithmods:corner_rock>.withTag({texture: {Name: "minecraft:brick_block"}}));
JEI.removeAndHide(<betterwithmods:corner_rock>.withTag({texture: {Name: "minecraft:nether_brick"}}));


var bricksNoMetadata as IIngredient[string] = {
    "contenttweaker:big_limestone_bricks": <contenttweaker:big_limestone_bricks>,
    "contenttweaker:big_chalk_bricks": <contenttweaker:big_chalk_bricks>,
    "contenttweaker:big_shale_bricks": <contenttweaker:big_shale_bricks>,
    "contenttweaker:fancy_limestone": <contenttweaker:fancy_limestone>,
    "contenttweaker:brick_minecraft_stone": <contenttweaker:brick_minecraft_stone>,
    "contenttweaker:brick_aether_legacy_holystone": <contenttweaker:brick_aether_legacy_holystone>,
    "contenttweaker:brick_quark_sandstone": <contenttweaker:brick_quark_sandstone>,
    "contenttweaker:brick_quark_red_sandstone": <contenttweaker:brick_quark_red_sandstone>,
    "contenttweaker:brick_white_sandstone": <contenttweaker:brick_white_sandstone>,
    "contenttweaker:brick_red_granite_sandstone": <contenttweaker:brick_red_granite_sandstone>,
    "contenttweaker:brick_quark_soul_sandstone": <contenttweaker:brick_quark_soul_sandstone>,
    "contenttweaker:brick_biomesoplenty_mud": <contenttweaker:brick_biomesoplenty_mud>,
    "contenttweaker:brick_earthworks_adobe": <contenttweaker:brick_earthworks_adobe>,
    "contenttweaker:brick_quark_brimstone": <contenttweaker:brick_quark_brimstone>,
    "contenttweaker:brick_quark_permafrost": <contenttweaker:brick_quark_permafrost>,
    "contenttweaker:brick_minecraft_clay": <contenttweaker:brick_minecraft_clay>,
    "contenttweaker:brick_quark_sandy": <contenttweaker:brick_quark_sandy>,
    "contenttweaker:brick_pyrotech_masonry": <contenttweaker:brick_pyrotech_masonry>,
    "contenttweaker:brick_pyrotech_refractory": <contenttweaker:brick_pyrotech_refractory>,
    "contenttweaker:brick_minecraft_nether": <contenttweaker:brick_minecraft_nether>,
    "contenttweaker:brick_netherex_fiery": <contenttweaker:brick_netherex_fiery>,
    "contenttweaker:brick_minecraft_end": <contenttweaker:brick_minecraft_end>,
    "contenttweaker:brick_betterwithaddons_whitebrick": <contenttweaker:brick_betterwithaddons_whitebrick>,
    "contenttweaker:brick_ceramics_porcelain": <contenttweaker:brick_ceramics_porcelain>,
    "contenttweaker:big_serpentinite_bricks": <contenttweaker:big_serpentinite_bricks>,
    "contenttweaker:big_chert_bricks": <contenttweaker:big_chert_bricks>,
    "contenttweaker:big_greywacke_bricks": <contenttweaker:big_greywacke_bricks>,
    "contenttweaker:big_dolomite_bricks": <contenttweaker:big_dolomite_bricks>,
    "contenttweaker:big_lignite_bricks": <contenttweaker:big_lignite_bricks>,
    "contenttweaker:big_siltstone_bricks": <contenttweaker:big_siltstone_bricks>,
    "betternether:cincinnasite_block" : <betternether:cincinnasite_block>,
    "betternether:cincinnasite_forged" : <betternether:cincinnasite_forged>,
    "betternether:cincinnasite_tile_large" : <betternether:cincinnasite_tile_large>,
    "betternether:cincinnasite_tile_small" : <betternether:cincinnasite_tile_small>,
    "betternether:cincinnasite_carved" : <betternether:cincinnasite_carved>,
    "betternether:cincinnasite_pillar" : <betternether:cincinnasite_pillar>,
    "quark:magma_bricks" : <quark:magma_bricks>,
    "quark:snow_bricks" : <quark:snow_bricks>,
    "quark:charred_nether_bricks" : <quark:charred_nether_bricks>
} as IIngredient[string];

for tag, block in bricksNoMetadata{
    Anvil.addShapedFixed(<betterwithmods:siding_rock>.withTag({texture: {Name: tag}})*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed(<betterwithmods:moulding_rock>.withTag({texture: {Name: tag}})*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:siding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:siding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:siding_rock>.withTag({texture: {Name: tag}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed(<betterwithmods:corner_rock>.withTag({texture: {Name: tag}})*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:moulding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:moulding_rock>.withTag({texture: {Name: tag}}), <betterwithmods:moulding_rock>.withTag({texture: {Name: tag}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Name: tag}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Name: tag}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Name: tag}}));
}

var bricksMetadata as IIngredient[IData] = {
    {Properties: {variant: "prismarine_bricks"}, Name: "minecraft:prismarine"} : <minecraft:prismarine:1>,
    {Properties: {variant: "elder_prismarine_bricks"}, Name: "quark:elder_prismarine"} : <quark:elder_prismarine:1>,
    {Properties: {variant: "netherwrought_bricks"}, Name: "quark:polished_netherrack"} : <quark:polished_netherrack:1>
} as IIngredient[IData];

for nbt, block in bricksMetadata{
    Anvil.addShapedFixed(<betterwithmods:siding_rock>.withTag({texture: nbt})*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed(<betterwithmods:moulding_rock>.withTag({texture: nbt})*8, [
        [<betterwithmods:siding_rock>.withTag({texture: nbt}), <betterwithmods:siding_rock>.withTag({texture: nbt}), <betterwithmods:siding_rock>.withTag({texture: nbt}), <betterwithmods:siding_rock>.withTag({texture: nbt})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed(<betterwithmods:corner_rock>.withTag({texture: nbt})*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: nbt}), <betterwithmods:moulding_rock>.withTag({texture: nbt}), <betterwithmods:moulding_rock>.withTag({texture: nbt}), <betterwithmods:moulding_rock>.withTag({texture: nbt})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: nbt}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: nbt}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: nbt}));
}

var nonStandardPlanks as IIngredient[string] = {
    "aether_legacy:skyroot_plank" : <aether_legacy:skyroot_plank>,
    "twilightforest:sort_planks" : <twilightforest:sort_planks>,
    "twilightforest:mangrove_planks" : <twilightforest:mangrove_planks>,
    "twilightforest:trans_planks" : <twilightforest:trans_planks>,
    "twilightforest:dark_planks" : <twilightforest:dark_planks>,
    "twilightforest:twilight_oak_planks" : <twilightforest:twilight_oak_planks>,
    "twilightforest:canopy_planks" : <twilightforest:canopy_planks>,
    "twilightforest:mine_planks" : <twilightforest:mine_planks>
} as IIngredient[string];

for tag, block in nonStandardPlanks{
    Saw.add(block, [<betterwithmods:siding_wood>.withTag({texture: {Name: tag}})*2]);
    Saw.add(<betterwithmods:siding_wood>.withTag({texture: {Name: tag}}), [<betterwithmods:moulding_wood>.withTag({texture: {Name: tag}})*2]);
    Saw.add(<betterwithmods:moulding_wood>.withTag({texture: {Name: tag}}), [<betterwithmods:corner_wood>.withTag({texture: {Name: tag}})*2]);

    JEI.addItem(<betterwithmods:siding_wood>.withTag({texture: {Name: tag}}));
    JEI.addItem(<betterwithmods:moulding_wood>.withTag({texture: {Name: tag}}));
    JEI.addItem(<betterwithmods:corner_wood>.withTag({texture: {Name: tag}}));
}

val igneousBrickIDs as IIngredient[string] = {
    "red_granite" : <undergroundbiomes:igneous_brick>,
    "black_granite" : <undergroundbiomes:igneous_brick:1>,
    "rhyolite" : <undergroundbiomes:igneous_brick:2>,
    "andesite" : <undergroundbiomes:igneous_brick:3>,
    "gabbro" : <undergroundbiomes:igneous_brick:4>,
    "basalt" : <undergroundbiomes:igneous_brick:5>,
    "komatite" : <undergroundbiomes:igneous_brick:6>,
    "dacite" : <undergroundbiomes:igneous_brick:7>
} as IIngredient[string];

for tag, block in igneousBrickIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_brick"}}));
}

val igneousCobbleIDs as IIngredient[string] = {
    "red_granite" : <undergroundbiomes:igneous_cobble>,
    "black_granite" : <undergroundbiomes:igneous_cobble:1>,
    "rhyolite" : <undergroundbiomes:igneous_cobble:2>,
    "andesite" : <undergroundbiomes:igneous_cobble:3>,
    "gabbro" : <undergroundbiomes:igneous_cobble:4>,
    "basalt" : <undergroundbiomes:igneous_cobble:5>,
    "komatite" : <undergroundbiomes:igneous_cobble:6>,
    "dacite" : <undergroundbiomes:igneous_cobble:7>
} as IIngredient[string];

for tag, block in igneousBrickIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_cobble"}}));
}

val igneousStoneIDs as IIngredient[string] = {
    "red_granite" : <undergroundbiomes:igneous_stone>,
    "black_granite" : <undergroundbiomes:igneous_stone:1>,
    "rhyolite" : <undergroundbiomes:igneous_stone:2>,
    "andesite" : <undergroundbiomes:igneous_stone:3>,
    "gabbro" : <undergroundbiomes:igneous_stone:4>,
    "basalt" : <undergroundbiomes:igneous_stone:5>,
    "komatite" : <undergroundbiomes:igneous_stone:6>,
    "dacite" : <undergroundbiomes:igneous_stone:7>
} as IIngredient[string];

for tag, block in igneousStoneIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:igneous_stone"}}));
}

val metamorphicBrickIDs as IIngredient[string] = {
    "gniess" : <undergroundbiomes:metamorphic_brick>,
    "eclogite" : <undergroundbiomes:metamorphic_brick:1>,
    "marble" : <undergroundbiomes:metamorphic_brick:2>,
    "quartzite" : <undergroundbiomes:metamorphic_brick:3>,
    "blue_schist" : <undergroundbiomes:metamorphic_brick:4>,
    "green_schist" : <undergroundbiomes:metamorphic_brick:5>,
    "soapstone" : <undergroundbiomes:metamorphic_brick:6>,
    "migmatite" : <undergroundbiomes:metamorphic_brick:7>
} as IIngredient[string];

for tag, block in metamorphicBrickIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);   

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_brick"}}));
}

val metamorphicCobbleIDs as IIngredient[string] = {
    "gniess" : <undergroundbiomes:metamorphic_cobble>,
    "eclogite" : <undergroundbiomes:metamorphic_cobble:1>,
    "marble" : <undergroundbiomes:metamorphic_cobble:2>,
    "quartzite" : <undergroundbiomes:metamorphic_cobble:3>,
    "blue_schist" : <undergroundbiomes:metamorphic_cobble:4>,
    "green_schist" : <undergroundbiomes:metamorphic_cobble:5>,
    "soapstone" : <undergroundbiomes:metamorphic_cobble:6>,
    "migmatite" : <undergroundbiomes:metamorphic_cobble:7>
} as IIngredient[string];

for tag, block in metamorphicCobbleIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);   

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_cobble"}}));
}

val metamorphicStoneIDs as IIngredient[string] = {
    "gniess" : <undergroundbiomes:metamorphic_stone>,
    "eclogite" : <undergroundbiomes:metamorphic_stone:1>,
    "marble" : <undergroundbiomes:metamorphic_stone:2>,
    "quartzite" : <undergroundbiomes:metamorphic_stone:3>,
    "blue_schist" : <undergroundbiomes:metamorphic_stone:4>,
    "green_schist" : <undergroundbiomes:metamorphic_stone:5>,
    "soapstone" : <undergroundbiomes:metamorphic_stone:6>,
    "migmatite" : <undergroundbiomes:metamorphic_stone:7>
} as IIngredient[string];

for tag, block in metamorphicStoneIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);   

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:metamorphic_stone"}}));
}

val sedimentaryStoneIDs as IIngredient[string] = {
    "limestone" : <undergroundbiomes:sedimentary_stone>,
    "chalk" : <undergroundbiomes:sedimentary_stone:1>,
    "shale" : <undergroundbiomes:sedimentary_stone:2>,
    "siltstone" : <undergroundbiomes:sedimentary_stone:3>,
    "lignite" : <undergroundbiomes:sedimentary_stone:4>,
    "dolomite" : <undergroundbiomes:sedimentary_stone:5>,
    "greywacke" : <undergroundbiomes:sedimentary_stone:6>,
    "chert" : <undergroundbiomes:sedimentary_stone:7>
} as IIngredient[string];

for tag, block in sedimentaryStoneIDs{
    Anvil.addShapedFixed((<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}))*8, [
        [block, block, block, block],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}))*8, [
        [<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);
    Anvil.addShapedFixed((<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}))*8, [
        [<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}), <betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}})],
        [null, null, null, null], 
        [null, null, null, null], 
        [null, null, null, null]
    ]);

    JEI.addItem(<betterwithmods:siding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}));
    JEI.addItem(<betterwithmods:moulding_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}));
    JEI.addItem(<betterwithmods:corner_rock>.withTag({texture: {Properties: {type: tag}, Name: "undergroundbiomes:sedimentary_stone"}}));
}