# When adding a new gamestage, dimension, or spawning rule, add it to this comment and add another comment in the category itself
# Dimensions:
# Gamestages:
# Biomes:

[[modify]]
    
	new_group = "hostile"
        [modify.entity]
        entity = "primitivemobs:trollager"
[[modify]]
    
	new_group = "hostile"
        [modify.entity]
        entity = "primitivemobs:skeleton_warrior"
[[modify]]
    
	new_group = "hostile"
        [modify.entity]
        entity = "primitivemobs:goblin"
[[modify]]
    
	new_group = "hostile"
        [modify.entity]
        entity = "primitivemobs:rocket_creeper"