# When adding a new gamestage, dimension, or spawning rule, add it to this comment and add another comment in the category itself
# Dimensions: Overworld [0] Nether [-1] End [1] Aether [4] Twilight Forest [7] Beneath [10]
# Gamestages:
# Biomes:

# Disabled Mobs
# Creepers do not spawn in Nether, End or Aether
[[remove]]
    dimension = [1, -1, 4]
    [remove.entity]
        matcher = "minecraft:creeper"

# Wraiths do not spawn in OW, End, or Aether - update for 3.4 
[[remove]]
    dimension = [0, 1, 4]
    [remove.entity]
        matcher = "quark:wraith"

# Fugitives only spawn in the Overworld - update for 3.4 
[[remove]]
    dimension = [1, 4, 7, 10, -1]
    [remove.entity]
        matcher = "toroquest:toroquest_fugitive"

# Endermen do not spawn in the Twilight Forest or Nether
[[remove]]
    dimension = [7, -1]
    [remove.entity]
        matcher = "minecraft:enderman"

# Skeletons, zombies, pipers, lammergeiers, and zombie players do not spawn in the Aether
[[remove]]
    dimension = 4
    [remove.entity]
        matcher = "minecraft:skeleton"
[[remove]]
    dimension = 4
    [remove.entity]
        matcher = "minecraft:zombie"
[[remove]]
    dimension = 4
    [remove.entity]
        matcher = "rats:illager_piper"
[[remove]]
    dimension = 4
    [remove.entity]
        matcher = "betteranimalsplus:lammergeier"
[[remove]]
    dimension = 4
    [remove.entity]
        matcher = "zombie_players:zombie_player"

# Baby zombies do not spawn in the Nether
[[remove]]
    dimension = -1
    [remove.entity]
        matcher = "minecraft:zombie"

# Vanilla passive mobs, lava cows, aether swets do not spawn
[[remove]]
    [remove.entity]
        matcher = "minecraft:pig"
[[remove]]
    [remove.entity]
        matcher = "minecraft:sheep"
[[remove]]
    [remove.entity]
        matcher = "minecraft:cow"
[[remove]]
    [remove.entity]
        matcher = "minecraft:chicken"
[[remove]]
    [remove.entity]
        matcher = "minecraft:mooshroom"
[[remove]]
    [remove.entity]
        matcher = "minecraft:rabbit"
[[remove]]
    [remove.entity]
        matcher = "mod_lavacow:lavacow"
[[remove]]
    [remove.entity]
        matcher = "aether_legacy:swet"

# Ashen, skydrakes, snow villagers, and dread mobs (exception of the dread thrall) do not spawn in the Overworld
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "quark:ashen"
[[remove]]
    dimension = 0
    [remove.entity]        
        entity = "mowziesmobs:naga"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:dread_beast"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:dread_scuttler"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:dread_ghoul"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:dread_lich"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:dread_knight"
[[remove]]
    dimension = 0
    [remove.entity]
        matcher = "iceandfire:snowvillager"
[[remove]]
    [remove.entity]
        mod = "specialmobs"

# Harvester
[[remove]]
    dimension = 0 
    [remove.entity]
        matcher = "mod_lavacow:weta"

# Aether
[[remove]]
    [remove.entity]
        matcher = "mowziesmobs:naga"

# Beneath
[[remove]]
    [remove.entity]
        matcher = "mod_lavacow:zombiemushroom"
[[remove]]
    [remove.entity]
        matcher = "mod_lavacow:zombiefrozen"

# Mythril
[[remove]]
    [remove.entity]
        matcher = "trumpetskeleton:trumpet_skeleton"

# Ghast Queen

