# When adding a new gamestage, dimension, or spawning rule, add it to this comment and add another comment in the category itself
# Dimensions:
# Gamestages:
# Biomes:
more_logging = true
# Overworld Stage (stageless)
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:zombie"
        min_group_size = 1
        max_group_size = 1
        weight = 100
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:skeleton"
        min_group_size = 1
        max_group_size = 1
        weight = 100
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:spider"
        min_group_size = 1
        max_group_size = 1
        weight = 100
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:creeper"
        min_group_size = 1
        max_group_size = 1
        weight = 75
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:enderman"
        min_group_size = 1
        max_group_size = 1
        weight = 25
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "quark:dweller"
        min_group_size = 1
        max_group_size = 1
        weight = 50
    [spawn.height]
        max = 50
        check_sky = true
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:witch"
        min_group_size = 1
        max_group_size = 1
        weight = 3

# Harvester Stage
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:windwitch"
        min_group_size = 1
        max_group_size = 1
        weight = 3
    [spawn.gamestage]
        gamestage = "killedharvester"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:silverfish"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.gamestage]
        gamestage = "killedharvester"
    [spawn.spawnblock]
        block = ["minecraft:sandstone", "minecraft:gravel", "undergroundbiomes:metamorphic_gravel", "undergroundbiomes:sedimentary_gravel", "undergroundbiomes:igneous_sand", "undergroundbiomes:metamorphic_sand", "undergroundbiomes:sedimentary_sand", "undergroundbiomes:igneous_sandstone", "undergroundbiomes:metamorphic_sandstone", "undergroundbiomes:sedimentary_sandstone", "biomesoplenty:white_sandstone", "minecraft:stone", "undergroundbiomes:igneous_stone", "undergroundbiomes:metamorphic_stone", "undergroundbiomes:igneous_overgrown", "undergroundbiomes:metamorphic_overgrown", "undergroundbiomes:sedimentary_stone", "undergroundbiomes:sedimentary_overgrown"]
    [spawn.height]
        max = 120
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:hungryzombie"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedharvester"

[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:sniperskeleton"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedharvester"

[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:hungryspider"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedharvester"

[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:palespider"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedharvester"
    [spawn.height]
        max = 80

[[spawn]]
    dimension = [4]
    group = "hostile"
    [spawn.entity]
        entity = "mowziesmobs:naga"
        min_group_size = 1
        max_group_size = 1
        weight = 5
    [spawn.biome]
        biome = "biometweaker:aether_cliffs"
    [spawn.gamestage]
        gamestage = "killedharvester"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:weta"
        min_group_size = 1
        max_group_size = 1
        weight = 75
    [spawn.biome]
        biome = ["biomesoplenty:alps","biomesoplenty:alps_foothills","biomesoplenty:mountain","biomesoplenty:mountain_foothills","minecraft:jungle","minecraft:jungle_hills","minecraft:jungle_edge","minecraft:mutated_jungle","minecraft:mutated_jungle_edge","biomesoplenty:rainforest","biomesoplenty:tropical_rainforest","minecraft:mutated_extreme_hills","biomesoplenty:brushland","biomesoplenty:grove","biomesoplenty:overgrown_cliffs","biomesoplenty:shrubland","biomesoplenty:tropical_island"]
    [spawn.gamestage]
        gamestage = "killedharvester"
    [spawn.light]
        max = 4
    [spawn.height]
        min = 55
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:pingu"
        min_group_size = 1
        max_group_size = 1
        weight = 75
    [spawn.biome]
        biome = ["minecraft:ice_flats","minecraft:mutated_ice_flats","minecraft:ice_mountains","biomesoplenty:cold_desert","biomesoplenty:tundra","iceandfire:glacier","biomesoplenty:snowy_tundra"]
    [spawn.gamestage]
        gamestage = "killedharvester"
    [spawn.height]
        min = 55
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:ptera"
        min_group_size = 1
        max_group_size = 1
        weight = 50
    [spawn.biome]
        biome = ["minecraft:jungle","minecraft:jungle_hills","minecraft:jungle_edge","minecraft:mutated_jungle","minecraft:mutated_jungle_edge","biomesoplenty:rainforest","biomesoplenty:tropical_rainforest","biomesoplenty:overgrown_cliffs","biomesoplenty:tropical_island","biomesoplenty:lush_swamp","biomesoplenty:mangrove","biomesoplenty:oasis","minecraft:desert","minecraft:desert_hills","minecraft:mesa","minecraft:mesa_rock","minecraft:mesa_clear_rock","minecraft:mutated_mesa minecraft:mutated_mesa_rock", "minecraft:mutated_mesa_clear_rock",]
    [spawn.block]
        block = ["minecraft:grass", "minecraft:sand", "minecraft:hardened_clay", "minecraft:sandstone", "minecraft:gravel", "undergroundbiomes:metamorphic_gravel", "undergroundbiomes:sedimentary_gravel", "undergroundbiomes:igneous_sand", "undergroundbiomes:metamorphic_sand", "undergroundbiomes:sedimentary_sand", "undergroundbiomes:igneous_sandstone", "biomesoplenty:grass", "undergroundbiomes:metamorphic_sandstone", "undergroundbiomes:sedimentary_sandstone", "biomesoplenty:white_sand", "biomesoplenty:white_sandstone", "biomesoplenty:dried_sand", "biomesoplenty:leaves_0", "biomesoplenty:leaves_1", "biomesoplenty:leaves_2", "biomesoplenty:leaves_3", "biomesoplenty:leaves_4", "biomesoplenty:leaves_5", "biomesoplenty:leaves_6", "dynamictrees:leaves0", "dynamictrees:leaves1", "dynamictreesbop:leaves0", "dynamictreesbop:leaves1", "dynamictreesbop:leaves2", "dynamictreesbop:leaves3", "dynamictreesbop:leaves4", "dynamictreesbop:leaves5", "dynamictreesbop:leaves6", "dynamictreesbop:leaves7"]
    [spawn.gamestage]
        gamestage = "killedharvester"
    [spawn.height]
        min = 70
    [spawn.light]
        max = 11
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "betterwithmods:bwm_jungle_spider"
        min_group_size = 1
        max_group_size = 1
        weight = 75
    [spawn.biome]
        biome = ["minecraft:jungle","minecraft:jungle_hills","minecraft:jungle_edge","minecraft:mutated_jungle","minecraft:mutated_jungle_edge","biomesoplenty:rainforest","biomesoplenty:tropical_rainforest","biomesoplenty:tropical_island"]
    [spawn.height]
        min = 60
    [spawn.light]
        max = 12
    [spawn.gamestage]
        gamestage = "killedharvester"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:scarecrow"
        min_group_size = 1
        max_group_size = 1
        weight = 5
    [spawn.biome]
        biome = ["minecraft:plains","minecraft:forest","minecraft:roofed_forest","minecraft:mutated_roofed_forest","minecraft:forest_hills","minecraft:birch_forest","minecraft:birch_forest_hills","minecraft:mutated_extreme_hills","minecraft:flower_forest","biomesoplenty:bayou","biomesoplenty:bog","biomesoplenty:chaparral","biomesoplenty:cherry_blossom_grove","biomesoplenty:dead_forest","biomesoplenty:grassland","biomesoplenty:grove","biomesoplenty:lavender_fields","biomesoplenty:maple_woods","biomesoplenty:ominous_woods","biomesoplenty:orchard","biomesoplenty:overgrown_cliffs","biomesoplenty:prairie","biomesoplenty:seasonal_forest","biomesoplenty:shrubland","biomesoplenty:temperate_rainforest","biomesoplenty:pasture","biomesoplenty:wasteland","biomesoplenty:woodland"]
    [spawn.height]
        min = 60
    [spawn.light]
        max = 12
    [spawn.gamestage]
        all_stages = true
        gamestage = "killedharvester"
        gamestage = "fall"

# Nether Stage
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:firezombie"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:firecreeper"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:fireskeleton"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "netherex:salamander"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
    [spawn.height]
        max = 48
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "magma_monsters:magma_monster_grunt"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
    [spawn.height]
        max = 40
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "netherex:ember"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "enterednether"
    [spawn.height]
        max = 50

# Aether Stage
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "aether_legacy:cockatrice"
        min_group_size = 1
        max_group_size = 1
        weight = 50
    [spawn.gamestage]
        gamestage = "enteredaether"
    [spawn.height]
        min = 120
    [spawn.light]
        max = 10

# Quazar Stage
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:jumpingcreeper"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedquazar"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:wildswitch"
        min_group_size = 1
        max_group_size = 1
        weight = 3
    [spawn.gamestage]
        gamestage = "killedquazar"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "minecraft:flyingsilverfish"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.gamestage]
        gamestage = "killedquazar"
    [spawn.spawnblock]
        block = ["minecraft:sandstone", "minecraft:gravel", "undergroundbiomes:metamorphic_gravel", "undergroundbiomes:sedimentary_gravel", "undergroundbiomes:igneous_sand", "undergroundbiomes:metamorphic_sand", "undergroundbiomes:sedimentary_sand", "undergroundbiomes:igneous_sandstone", "undergroundbiomes:metamorphic_sandstone", "undergroundbiomes:sedimentary_sandstone", "biomesoplenty:white_sandstone", "minecraft:stone", "undergroundbiomes:igneous_stone", "undergroundbiomes:metamorphic_stone", "undergroundbiomes:igneous_overgrown", "undergroundbiomes:metamorphic_overgrown", "undergroundbiomes:sedimentary_stone", "undergroundbiomes:sedimentary_overgrown"]
    [spawn.height]
        max = 120
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:desertspider"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedquazar"
    [spawn.biome]
        matcher = "desert"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:witchspider"
        min_group_size = 1
        max_group_size = 1
        weight = 100
    [spawn.gamestage]
        gamestage = "killedquazar"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "betteranimalsplus:feralwolf"
        min_group_size = 1
        max_group_size = 1
        weight = 100 
    [spawn.biome]
        biome = ["minecraft:taiga","minecraft:taiga_hills","minecraft:taiga_cold","minecraft:taiga_cold_hills","minecraft:redwood_taiga","minecraft:redwood_taiga_hills","minecraft:mutated_taiga","minecraft:mutated_taiga_cold","minecraft:mutated_redwood_taiga","minecraft:mutated_redwood_taiga_hills","minecraft:ice_flats","biomesoplenty:ice_mountains","minecraft:roofed_forest","minecraft:extreme_hills","minecraft:mutated_extreme_hills","minecraft:ice_spikes","minecraft:mutated_roofed_forest","biomesoplenty:alps","biomesoplenty:alps_foothills","biomesoplenty:boreal_forest","biomesoplenty:cold_desert","biomesoplenty:ominous_woods","biomesoplenty:snowy_coniferous_forest","biomesoplenty:snowy_forest","biomesoplenty:snowy_forest","biomesoplenty:tundra","biomesoplenty:snowy_tundra"]
    [spawn.gamestage]
            gamestage = "killedquazar"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:vespa"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.biome]
        biome = ["minecraft:jungle","minecraft:jungle_hills","minecraft:jungle_edge","minecraft:mutated_jungle","minecraft:mutated_jungle_edge","biomesoplenty:rainforest","biomesoplenty:tropical_rainforest","biomesoplenty:overgrown_cliffs","biomesoplenty:tropical_island","biomesoplenty:lush_swamp","biomesoplenty:mangrove","biomesoplenty:oasis"]
    [spawn.gamestage]
        gamestage = "killedquazar"
    [spawn.height]
        min = 70
    [spawn.light]
        max = 13

# Beneath Stage
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "mod_lavacow:undertaker"
        min_group_size = 1
        max_group_size = 1
        weight = 5
    [spawn.biome]
        biome = ["biomesoplenty:ominous_woods","biomesoplenty:wasteland","biomesoplenty:dead_forest"]
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [0,10]
    group = "hostile"
    [spawn.entity]
        entity = "betteranimalsplus:zotzpyre"
        min_group_size = 1
        max_group_size = 1
        weight = 30
    [spawn.height]
        max = 100
        check_sky = true
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:deathcreeper"
        min_group_size = 1
        max_group_size = 1
        weight = 75
[[spawn]]
    dimension = [10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:darkcreeper"
        min_group_size = 1
        max_group_size = 1
        weight = 75
[[spawn]]
    dimension = [0,10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:undeadwitch"
        min_group_size = 1
        max_group_size = 1
        weight = 3
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:blindingsilverfish"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.gamestage]
        gamestage = "enteredbeneath"
    [spawn.spawnblock]
        block = ["minecraft:sandstone", "minecraft:gravel", "undergroundbiomes:metamorphic_gravel", "undergroundbiomes:sedimentary_gravel", "undergroundbiomes:igneous_sand", "undergroundbiomes:metamorphic_sand", "undergroundbiomes:sedimentary_sand", "undergroundbiomes:igneous_sandstone", "undergroundbiomes:metamorphic_sandstone", "undergroundbiomes:sedimentary_sandstone", "biomesoplenty:white_sandstone", "minecraft:stone", "undergroundbiomes:igneous_stone", "undergroundbiomes:metamorphic_stone", "undergroundbiomes:igneous_overgrown", "undergroundbiomes:metamorphic_overgrown", "undergroundbiomes:sedimentary_stone", "undergroundbiomes:sedimentary_overgrown"]
    [spawn.height]
        max = 80
        check_sky = true
    [spawn.light]
        max = 5
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:poisonsilverfish"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.gamestage]
        gamestage = "enteredbeneath"
    [spawn.spawnblock]
        block = ["minecraft:sandstone", "minecraft:gravel", "undergroundbiomes:metamorphic_gravel", "undergroundbiomes:sedimentary_gravel", "undergroundbiomes:igneous_sand", "undergroundbiomes:metamorphic_sand", "undergroundbiomes:sedimentary_sand", "undergroundbiomes:igneous_sandstone", "undergroundbiomes:metamorphic_sandstone", "undergroundbiomes:sedimentary_sandstone", "biomesoplenty:white_sandstone", "minecraft:stone", "undergroundbiomes:igneous_stone", "undergroundbiomes:metamorphic_stone", "undergroundbiomes:igneous_overgrown", "undergroundbiomes:metamorphic_overgrown", "undergroundbiomes:sedimentary_stone", "undergroundbiomes:sedimentary_overgrown"]
    [spawn.height]
        max = 80
        check_sky = true
    [spawn.light]
        max = 5
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:plaguezombie"
        min_group_size = 1
        max_group_size = 1
        weight = 25
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:poisonskeleton"
        min_group_size = 1
        max_group_size = 1
        weight = 75
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:knightskeleton"
        min_group_size = 1
        max_group_size = 1
        weight = 60
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [0 , 10]
    group = "hostile"
    [spawn.entity]
        entity = "specialmobs:poisonspider"
        min_group_size = 1
        max_group_size = 1
        weight = 75
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [0]
    group = "hostile"
    [spawn.entity]
        entity = "rats:rat"
        min_group_size = 1
        max_group_size = 1
        weight = 20
    [spawn.gamestage]
        gamestage = "enteredbeneath"
[[spawn]]
    dimension = [10]
    group = "hostile"
    [spawn.entity]
        entity = "rats:ratlantean_spirit"
        min_group_size = 1
        max_group_size = 1
        weight = 20
    [spawn.height]
        max = 120
    [spawn.gamestage]
        gamestage = "enteredbeneath"
# Mythril Stage

# Ender Dragon Stage

# Wither Stage

# Ghast Queen Stage

